language: python
install: pip3 install SQLAlchemy
install: pip3 install -U pytest
install: pip3 install psycopg2-binary
install: apt-get install docker docker.io
install: sudo docker pull postgres
script: python3 ./n_queen_test.py
