language: python
services:
- postgressql
- docker
env:
- compose_file=docker-compose.yml
  global:
  - PGPORT=54320
before_install:
- sudo /etc/init.d/postgresql start
install: 
- pip install SQLAlchemy
- pip install -U pytest
- pip install psycopg2-binary
before_script:
 - psql -h localhost -p 54320 -U cuenca -d mydb
script: python3 ./n_queen_test.py
after_script:
  - sudo /etc/init.d/postgresql stop