language: python
install: pip install SQLAlchemy
install: pip install -U pytest
install: pip install psycopg2-binary
install: apt-get install docker docker.io
install: sudo docker pull postgres
script: python3 ./n_queen_test.py
