language: python 
python: "3.6.8"
services:
- postgressql
- docker
env:
  - COMPOSE_FILE=docker-compose.yml

install: 
- pip install SQLAlchemy
- pip install -U pytest
- pip install psycopg2-binary
before_script:
- docker-compose up -d

script:
- pytest ./n_queen_test.py

after_script:
- docker-compose down