language: python
services:
- postgres
before_install:
- sudo /etc/init.d/postgresql start
install: 
- pip install SQLAlchemy
- pip install -U pytest
- pip install psycopg2-binary
env:
  global:
  - PGPORT=54320
script: python3 ./n_queen_test.py
after_script:
  - sudo /etc/init.d/postgresql stop