language: python
services:
- postgressql
- docker
env:
  - COMPOSE_FILE=docker-compose.yml:docker-compose.override.travis.yml

install: 
- pip install SQLAlchemy
- pip install -U pytest
- pip install psycopg2-binary
script:
- docker-compose up -d
- pytest ./n_queen_test.py
- docker-compose down