version: "3"
services:
  db:
    image: "postgres"
    container_name: "cuenca_postgres"
    environment:
      - POSTGRES_USER=cuenca
      - POSTGRES_PASSWORD=mycu3nc4Us3r
      - POSTGRES_DB=mydb
    ports:
      - "5432"
    volumes:
      - ./postgres-data:/var/lib/postgresql/data